stages:
    - build
    - test
    - push

image: node:11.4

build:
  stage: build
  cache:
    paths:
      - node_modules/
  tags:
    - docker
  script:
    - npm install

test:
  stage: test
  dependencies:
    - build
  tags:
    - docker
  script:
    - npm run test
      
push to npm:
  stage: push
  tags:
    - docker
  script:
    - npm run publish
  only:
  - tags
