stages:
    - build
    - test
    - push

image: node:11.4

cache:
  paths:
    - node_modules/

build:
  stage: build
  tags:
    - docker
  script:
    - npm install

test:
  stage: test
  dependencies:
    - build
  tags:
    - docker
  script:
    - npm install
    - npm run test
      
push to npm:
  stage: push
  tags:
    - docker
  script:
    - npm run publish
  only:
  - tags
